from pathlib import Path
import json,os,hashlib,datetime,time
root=Path.cwd();b=root/'work/orchestration/campaign-continuity';out=b/'mission-three-segment-01';lease=json.loads((root/'work/local-render-profiles/current-campaign-3b89912-m1-03/owner.lock').read_text());assert lease['runId']=='bcf8ac55-e418-49e4-a3d6-b7e804ee31d3';rows=[json.loads(x) for x in (out/'actions.jsonl').read_text().splitlines()];loaded=next(r for r in rows if r['action']=='clean-segment-loaded');proof=next(r for r in rows if r['action']=='checkpoint-loaded');awaiting=next(r for r in rows if r['action']=='awaiting-input');s=json.loads((out/'m3-segment-opening.json').read_text());prior=json.loads((b/'mission-two-segment-01-predecessor-validation.json').read_text());assert loaded['previousRunId']==prior['previousRunId'] and loaded['inheritedActiveSeconds']==prior['cumulativeActiveSeconds'];assert len(prior['failures'])==3 and prior['failures'][-1]['kind']=='prior-harness-failure';assert s['level']==3 and s['paused'] and s['completedMissions']==[1,2];assert proof['saved']==proof['stored']==prior['checkpoint'];assert proof['identity']['newWorld'] and proof['identity']['newScene'] and proof['identity']['currentCorrespondence'];raw=(b/'mission-three-first-batch-ddef3ca.json').read_bytes();assert hashlib.sha256(raw).hexdigest()=='4936c5e9e4d42f3d728f236f57598f68ce82c56eb2fbeaf32c7e54bb09d2dfb5';dst=out/'commands/0001.json';assert not dst.exists();tmp=dst.with_suffix('.tmp')
with tmp.open('xb') as f:f.write(raw);f.flush();os.fsync(f.fileno())
os.rename(tmp,dst);record={'queuedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'runId':lease['runId'],'profileId':lease['profileId'],'awaitingAt':awaiting['at'],'batchSha256':hashlib.sha256(raw).hexdigest(),'checkpointLoaded':proof,'openingTurn':s['turn'],'sourceHead':'ddef3caa522d45168b16f290cc5b5a4d1541fce2','priorFailureRecords':prior['failures'],'initialHostAdmissionIssue':'First host-only admission script tried to read journey.json before the scenario writes it at first consumption. It terminated without queuing or delivering any input. This admission uses actual successful maintained predecessor/load log and hash-bound prior record; live journey history is verified after first consumption. No scenario/source change.'};p=b/'mission-three-first-batch-admission.json';p.write_text(json.dumps(record,indent=2)+'\n');print(json.dumps({'admitted':True,'queuedAt':record['queuedAt'],'awaitingAt':awaiting['at'],'turn':s['turn'],'runId':lease['runId']}),flush=True)
for _ in range(100):
 if (out/'journey.json').exists():
  j=json.loads((out/'journey.json').read_text());assert j['failures']==prior['failures'];print(json.dumps({'actualJourneyRetains':len(j['failures']),'journeySha256AtObservation':hashlib.sha256((out/'journey.json').read_bytes()).hexdigest()}),flush=True);break
 time.sleep(.1)
