import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {execFileSync} from 'node:child_process'
import {campaignActive,requireLoadedCheckpoint,requireContinueBoundary,requireCampaignBudget} from '../../../../qa/campaign-continuity/boundaries.mjs'
import {requireConversion,requireCurrentConvertedWorker,acceptedOrderEvidence} from '../../../../qa/campaign-continuity/observation.mjs'
import {requireErosionEvidence} from '../../../../qa/campaign-continuity/erosion-observer.mjs'
const b='work/orchestration/campaign-continuity',p=b+'/mission-three-segment-02-erosion-prefix', read=file=>JSON.parse(readFileSync(file)),hash=bytes=>createHash('sha256').update(bytes).digest('hex'),sha=file=>hash(readFileSync(file))
const prefix=read(p+'/prefix.json'),journal=readFileSync(p+'/actions-through-0002.jsonl'),actions=journal.toString().trim().split('\n').map(JSON.parse)
assert.equal(sha(p+'/prefix.json'),'ba8f7923054d57c0b9c2dadc09a7fa589c14c03d897c829332bf3ccac34435d7');assert.equal(hash(journal),prefix.cutoff.journalSha256);assert.equal(actions.length,53)
const liveJournal=readFileSync(b+'/mission-three-segment-02/actions.jsonl');assert.ok(liveJournal.subarray(0,journal.length).equals(journal))
for(const f of prefix.files){assert.equal(sha(p+'/'+f.path),f.sha256,f.path);assert.equal(readFileSync(p+'/'+f.path).length,f.bytes);assert.equal(sha(f.source),f.sha256,f.source)}
assert.equal(execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),prefix.sourceHead);assert.equal(execFileSync('git',['status','--short'],{encoding:'utf8'}),'')
for(const name of ['scenario.mjs','boundaries.mjs','routes.mjs','run-policy.json','observation.mjs','erosion-observer.mjs','queued-stop.mjs','command-probes.mjs']) assert.equal(sha(b+'/mission-three-segment-02/'+name),sha('qa/campaign-continuity/'+name))
const batch1=read(p+'/consumed-0001.json'),batch2=read(p+'/consumed-0002.json');assert.deepEqual([...batch1,...batch2],actions.filter(row=>row.action==='requested-command').map(row=>row.command));assert.equal(actions.at(-1).next,'0003.json');assert.equal(actions.at(-1).paused,true)
assert.ok(!actions.some(row=>row.action.includes('failed')||row.action==='diagnostic-stop'||row.action==='required-actor-unavailable'||row.action==='queued-preserving-stop-consumed'))
const load=actions.find(row=>row.action==='checkpoint-loaded');requireLoadedCheckpoint(load.saved,load.boundary,load.stored);requireContinueBoundary(load.identity,3);assert.equal(load.saved.turn,7424)
const admission=read(p+'/admission.json'),opening=read(p+'/m3-segment-opening.json');assert.equal(admission.runId,prefix.runId);assert.equal(admission.openingSha256,sha(p+'/m3-segment-opening.json'));assert.equal(admission.firstBatchSha256,sha(p+'/consumed-0001.json'));assert.equal(opening.paused,true);assert.deepEqual(opening.completedMissions,[1,2])
const prior=read(p+'/prior-journey.json'),converted=read(p+'/m3-restored-conversion-worker.json'),cutoff=read(p+'/batch-0002.json');const epochs=[...prior.epochs,prior.currentEpoch]
assert.equal(converted.observation.name,'reload-3-8');assert.equal(cutoff.observation.name,'reload-3-8');assert.notEqual(cutoff.observation.name,prior.currentEpoch.name)
const conversion=requireConversion(converted.observation,2631,3181);assert.deepEqual(conversion,prefix.currentConversion.event);assert.equal(conversion.replacements[0].id,3298);assert.equal(requireCurrentConvertedWorker(converted,2631,3181,3298).hp,50)
const order=actions.find(row=>row.action==='world-order-observation'),accepted=actions.find(row=>row.action==='world-order-input-observed');assert.deepEqual(acceptedOrderEvidence(order.before,order.after,order.hit),accepted.acceptance);assert.deepEqual(accepted.acceptance.recipientIds,[3298]);assert.deepEqual(order.before.selected,[3298]);assert.deepEqual(order.after.selected,[3298]);assert.equal(order.after.units[0].order.model,27);assert.equal(order.after.units[0].order.a,101)
const worker=actions.find(row=>row.action==='erosion-named-worker');assert.deepEqual(worker,prefix.namedWorker);assert.deepEqual(worker.preacherOrderBefore,worker.preacherOrderAfter);assert.equal(worker.preacherOrderBefore.model,17)
const pointer=actions.find(row=>row.action==='entity-delivered-pointer-observation').observed;assert.equal(pointer.restored,true);assert.deepEqual(pointer.errors,[]);assert.equal(pointer.events.length,2);assert.ok(pointer.events.every(e=>e.trusted&&e.canvasTarget&&e.canvasOwned&&e.state.currentSceneMatches&&e.state.currentWorldMatches))
const evidence=requireErosionEvidence(cutoff.observation,101,true);assert.equal(evidence.armedAtTurn,8367);assert.equal(evidence.initialUses,0);assert.deepEqual(evidence.existingIds,[]);assert.deepEqual(evidence.use,prefix.headUse);assert.equal(evidence.effects.length,1)
const effect=evidence.effects[0];assert.equal(effect.onset.id,3322);assert.equal(effect.onset.age,0);assert.equal(effect.onset.remaining,64);assert.deepEqual(effect.samples,Array.from({length:64},(_,i)=>[8824+i,64-i]));assert.deepEqual(effect.retired,prefix.effect.retired);assert.equal(effect.retired.age,effect.retired.duration)
const onset=effect.terrain.onset.cells,retired=effect.terrain.retired.cells;assert.equal(onset.length,169);assert.equal(retired.length,169);assert.deepEqual(onset.map(c=>c.index),retired.map(c=>c.index));assert.equal(new Set(onset.map(c=>c.index)).size,169)
const changed=retired.filter((c,i)=>c.height!==onset[i].height||JSON.stringify(c.walkMasks)!==JSON.stringify(onset[i].walkMasks));assert.deepEqual(changed,effect.changedCells);assert.equal(changed.length,99)
const heightCells=retired.filter((c,i)=>c.height!==onset[i].height).length,maskCells=retired.filter((c,i)=>JSON.stringify(c.walkMasks)!==JSON.stringify(onset[i].walkMasks)).length
let changedMaskBits=0;retired.forEach((c,i)=>c.walkMasks.forEach((mask,k)=>mask.forEach((bit,q)=>{if(bit!==onset[i].walkMasks[k][q])changedMaskBits++})))
for(const e of [...epochs,cutoff.observation]){assert.deepEqual(e.errors,[]);assert.deepEqual(e.speedViolations,[])}
assert.equal(cutoff.observation.samples,cutoff.observation.lastTurn-cutoff.observation.firstTurn+1);assert.equal(evidence.samples,evidence.lastTurn-evidence.armedAtTurn)
const total=campaignActive(epochs,cutoff.observation),m3=campaignActive(epochs,cutoff.observation,3),anchor=prior.milestones.find(m=>m.level===3&&m.name==='conversion').missionActiveSeconds;assert.equal(total,prefix.budgets.campaignActive);assert.equal(m3,prefix.budgets.M3Active);assert.equal(anchor,prefix.budgets.originalConversionAnchor);requireCampaignBudget(epochs,cutoff.observation,3,read(p+'/run-policy.json').limits,anchor)
assert.equal(cutoff.turn,9047);assert.equal(cutoff.paused,true);assert.equal(cutoff.status,'playing');assert.deepEqual(cutoff.completedMissions,[1,2]);assert.equal(cutoff.units.find(u=>u.id===3298).hp,50);assert.equal(cutoff.units.find(u=>u.id===3181).hp,55)
const result={status:'PASS BROWSER PREFIX',reviewedAt:new Date().toISOString(),prefixSha256:sha(p+'/prefix.json'),artifactCopies:prefix.files.length,journalLines:53,journalSha256:hash(journal),currentEpoch:cutoff.observation.name,logicalEffectSamples:64,effectOnsetTurn:8824,effectZeroRemovalTurn:8888,changedCells:99,heightChangedCells:heightCells,walkMaskChangedCells:maskCells,individualWalkMaskBitsChanged:changedMaskBits,totalActiveSeconds:total,M3ActiveSeconds:m3,originalConversionAnchor:anchor,cutoffTurn:9047,cutoffState:'paused playing; completed[1,2]',claimScope:'Current conversion, actual named-Brave input and shrine-linked lifecycle through cutoff only; no terminal/victory/native replay claim.'}
const file=b+'/review-mission-three-segment-02-erosion-prefix/verification.json';writeFileSync(file,JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({path:file,sha256:sha(file),...result}))
