import assert from 'node:assert/strict';
import test from 'node:test';
import { createWorld, tick, cast, command, select, placeBuilding, findPath, walkable, height, HOME, ENEMY } from '../app/model.ts';
const advance = (w, seconds) => { for (let i = 0; i < seconds * 30; i++) tick(w, 1 / 30); };
test('a complete playable loop: selection, paths, conversion, building, training, combat, and end states', () => {
  const w = createWorld();
  assert.ok(w.units.every(u => walkable(w.terrain, u)), 'all followers start on dry land');
  assert.ok(w.buildings.every(b => walkable(w.terrain, b)), 'all structures start on dry land');
  assert.ok(findPath(w.terrain, HOME, ENEMY).length, 'tribes have a reachable land route');
  assert.equal(findPath(w.terrain, HOME, { x: -46, z: -46 }).length, 0, 'no walking across deep water');
  const start = w.mana;
  assert.equal(cast(w, 'convert', { x: -7, z: 0 }), true);
  assert.ok(w.units.filter(u => u.team === 'blue').length > 13);
  assert.equal(w.mana, start - 20);
  assert.equal(cast(w, 'convert', { x: -40, z: 40 }), false);
  assert.equal(w.mana, start - 20, 'invalid casts do not spend mana');
  select(w, 'shaman'); command(w, { x: -8, z: 9 }); advance(w, 8);
  assert.ok(Math.hypot(w.units[0].x + 8, w.units[0].z - 9) < 1, 'shaman reaches commanded destination');
  assert.equal(placeBuilding(w, 'hut', { x: -46, z: -46 }), false);
  const wood = w.wood;
  assert.equal(placeBuilding(w, 'camp', { x: -9, z: 12 }), true, 'place accessible camp');
  assert.equal(w.wood, wood - 65);
  advance(w, 25);
  assert.equal(w.buildings.find(b => b.kind === 'camp').progress, 1);
  assert.ok(w.units.filter(u => u.team === 'blue' && u.kind === 'warrior').length > 3, 'completed camp trains braves');
  const before = w.time; w.paused = true; tick(w, 1); assert.equal(w.time, before); w.paused = false;
  w.mana = 300; const h = height(w.terrain, 0, 0); assert.ok(cast(w, 'volcano', { x: 0, z: 0 })); assert.ok(height(w.terrain, 0, 0) > h + 10);
  const q = createWorld(); q.mana = 0; assert.equal(cast(q, 'blast', HOME), false); assert.equal(q.mana, 0);
  const s = q.units.find(u => u.kind === 'shaman' && u.team === 'blue'); s.hp = 0; tick(q, 1 / 30); assert.ok(q.respawn > 0); advance(q, 13); assert.ok(q.units.some(u => u.kind === 'shaman' && u.team === 'blue'), 'shaman reincarnates');
  q.units = q.units.filter(u => u.team !== 'red'); q.buildings = q.buildings.filter(b => b.team !== 'red'); tick(q, 1 / 30); assert.equal(q.status, 'won');
  const combat = createWorld(); combat.mana = 300; const caster = combat.units.find(u => u.team === 'blue' && u.kind === 'shaman'); caster.x = 6; caster.z = -5;
  const victim = combat.units.find(u => u.team === 'red' && u.kind === 'warrior'); assert.ok(cast(combat, 'lightning', victim)); tick(combat, 1/30); assert.ok(!combat.units.some(u => u.id === victim.id), 'lightning defeats a targeted warrior');
  assert.ok(cast(combat, 'earthquake', {x:19,z:-15})); tick(combat,1/30); assert.ok(combat.buildings.filter(b=>b.team==='red').length < 4, 'earthquake destroys enemy structures');
  const raid = createWorld(); raid.nextRaid = 0; tick(raid,1/30); assert.ok(raid.units.some(u=>u.team==='red' && u.target !== null && u.path.length),'enemy AI launches a reachable raid');
  const lost = createWorld(); lost.units = lost.units.filter(u => u.team !== 'blue'); tick(lost, 1 / 30); assert.equal(lost.status, 'lost');
});
