import assert from 'node:assert/strict'
import {readFileSync,writeFileSync} from 'node:fs'
import {createHash} from 'node:crypto'
import {execFileSync} from 'node:child_process'
import {campaignActive,requireCampaignBudget,requireCampaignProfile,requireLoadedCheckpoint,requireContinueBoundary} from '../../../../qa/campaign-continuity/boundaries.mjs'
import {requireErosionEvidence} from '../../../../qa/campaign-continuity/erosion-observer.mjs'
const base='work/orchestration/campaign-continuity',run=base+'/mission-three-segment-02',out=base+'/review-mission-three-segment-02'
const read=p=>JSON.parse(readFileSync(p)),hash=b=>createHash('sha256').update(b).digest('hex'),sha=p=>hash(readFileSync(p))
const packetPath=base+'/mission-three-segment-02-terminal-packet.json',packet=read(packetPath)
assert.equal(sha(packetPath),process.argv[2],'Frozen owner packet hash')
for(const row of packet.files){assert.ok(!row.path.includes('local-render-profiles')&&!row.path.includes('node_modules'),'Public evidence only');const bytes=readFileSync(row.path);assert.equal(hash(bytes),row.sha256,row.path);assert.equal(bytes.length,row.bytes,row.path)}
const receipt=read(run+'/receipt.json'),journey=read(run+'/journey.json'),terminal=read(run+'/terminal.json'),victory=read(run+'/m3-genuine-campaign-victory-result.json'),outer=read(base+'/mission-three-segment-02.outer.json'),launcher=read(base+'/mission-three-segment-02.launcher.json'),prior=read(base+'/mission-three-segment-01/journey.json')
const actions=readFileSync(run+'/actions.jsonl','utf8').trim().split('\n').map(JSON.parse)
assert.equal(actions.length,254);assert.equal(receipt.profile.runId,'ce37f851-390c-473a-a68e-bbfc05f900e2');assert.equal(receipt.profile.id,'7c15026e-2bb3-41e9-83e9-ce408b869416')
assert.equal(execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),'b45073eb75f8e2c8aa66ef809e76eaf621a68fc0');assert.equal(execFileSync('git',['status','--short'],{encoding:'utf8'}),'');assert.equal(execFileSync('git',['rev-parse','HEAD:app'],{encoding:'utf8'}).trim(),'20b5894d4c17f120cd7608b4138953ea6c5f243f')
for(const name of ['scenario.mjs','boundaries.mjs','routes.mjs','run-policy.json','observation.mjs','erosion-observer.mjs','queued-stop.mjs','command-probes.mjs'])assert.equal(sha(run+'/'+name),sha('qa/campaign-continuity/'+name))
assert.deepEqual(receipt.source,receipt.sourceAfter);assert.deepEqual(receipt.runtime,receipt.runtimeAfter);assert.deepEqual(receipt.scenario,receipt.scenarioAfter);assert.equal(receipt.scenario.sha256,sha('qa/campaign-continuity/scenario.mjs'));assert.equal(receipt.source.fingerprint,'5f36e2f0ddd2825514ba385c768449b0d02501a994f0501be3a203011a0e517f')
assert.deepEqual(launcher.sourceRuntimeVerification.source,receipt.source);assert.deepEqual(launcher.sourceRuntimeVerification.runtime,receipt.runtime);assert.deepEqual(launcher.sourceRuntimeVerification.inputs,receipt.profile.inputs);assert.equal(launcher.innerReceiptSha256,sha(run+'/receipt.json'))
assert.equal(outer.status,'failed');assert.equal(outer.phase,'finished');assert.equal(outer.exitCode,1);assert.equal(outer.signal,null);assert.deepEqual(outer.source,outer.sourceAfter);assert.equal(launcher.status,'terminal');assert.equal(launcher.commandExitCode,1);assert.equal(launcher.originClosed,true);assert.ok(launcher.postTcp.length===2&&launcher.postTcp.every(p=>p.port===4375&&p.closed&&p.code===111))
for(const k of ['stdout','stderr'])assert.equal(sha(outer.artifacts[k]),outer[k+'Sha256'])
assert.equal(receipt.status,'failed');assert.equal(receipt.profile.cleanupVerified,true);assert.equal(receipt.profile.continuationVerified,true);assert.deepEqual(receipt.errors,[]);assert.ok(!Object.hasOwn(receipt,'previousFailure'));assert.ok(!Object.hasOwn(receipt.profile,'checkpointReadFailure'));assert.equal(receipt.failure,journey.controlStops.at(-1).error);assert.ok(receipt.failure.startsWith('IncompleteRun: Requested bounded stop with committed latest preserved'))
assert.deepEqual(journey.failures,prior.failures);assert.deepEqual(journey.controlStops.slice(0,-1),prior.controlStops);assert.equal(journey.failures.length,3);assert.equal(journey.controlStops.length,2);assert.equal(journey.controlStops[0].code,'progress-stall');assert.equal(journey.controlStops[1].code,'preserve-latest');assert.equal(journey.preserveStopRequested,true);assert.equal(journey.preserveVerificationFailed,false);assert.deepEqual(journey.browserErrors,[])
assert.deepEqual(journey.epochs.slice(0,prior.epochs.length),prior.epochs);const retained=structuredClone(journey.epochs.at(-1));delete retained.retainedTerminalObservation;assert.deepEqual(retained,prior.currentEpoch);assert.equal(journey.epochs.at(-1).retainedTerminalObservation.runId,'bcf8ac55-e418-49e4-a3d6-b7e804ee31d3')
assert.deepEqual(journey.milestones.slice(0,prior.milestones.length),prior.milestones)
const current=journey.currentEpoch;assert.equal(current.name,'reload-3-8');assert.equal(current.samples,6042);assert.equal(current.samples,current.lastTurn-current.firstTurn+1);assert.deepEqual(current,terminal.observation)
for(const epoch of [...journey.epochs,current]){assert.deepEqual(epoch.errors,[]);assert.deepEqual(epoch.speedViolations,[])}
const load=actions.find(x=>x.action==='checkpoint-loaded');requireLoadedCheckpoint(load.saved,load.boundary,load.stored);requireContinueBoundary(load.identity,3);assert.equal(load.saved.turn,7424);assert.equal(actions.filter(x=>x.action==='checkpoint-loaded').length,1)
const profileReads=actions.filter(x=>x.action==='campaign-profile-readback');assert.equal(profileReads.length,2);requireCampaignProfile(profileReads[0].profile,[1,2]);requireCampaignProfile(profileReads[1].profile,[1,2,3]);assert.equal(profileReads[1].sha256,hash(JSON.stringify(profileReads[1].profile)));assert.equal(profileReads[1].at,'2026-10-05T22:51:34.515Z')
for(const s of [terminal,victory]){assert.equal(s.level,3);assert.equal(s.turn,13480);assert.equal(s.status,'won');assert.equal(s.paused,true);assert.deepEqual(s.completedMissions,[1,2,3]);assert.equal(s.units.filter(u=>u.team==='yellow').length,0);assert.equal(s.units.filter(u=>u.team==='blue'&&u.kind==='warrior').length,5);assert.deepEqual(s.buildings.filter(b=>b.team==='yellow').map(b=>[b.id,b.kind,b.hp,b.inside]),[[1023,'tower',52,0],[1022,'temple',65,0]])}
assert.match(victory.body,/Level Won/);assert.match(victory.body,/Continue to Mission 4/);assert.equal(victory.stats.cast,0);assert.equal(victory.stats.built,9);assert.ok(actions.every(x=>x.level===3));assert.ok(!actions.some(x=>x.action==='requested-command'&&['continue','finish'].includes(x.command.action)))
const saved=receipt.profile.checkpoints.find(x=>x.label==='m3-m3-erosion-complete').checkpoint;assert.equal(saved.turn,9047);assert.equal(saved.checkpointSha256,'ea74a69178c1aef6658c920058f97a1a71a0e32deeee681c7c347f399eb092ab');assert.deepEqual(saved,journey.protectedLatest.checkpoint);assert.deepEqual(saved,receipt.profile.checkpointAtEnd);for(const row of receipt.profile.checkpoints.filter(x=>['campaign stop preserve latest','campaign terminal latest'].includes(x.label)))assert.deepEqual(row.checkpoint,saved)
assert.equal(actions.filter(x=>x.action==='checkpoint-persisted').length,1);assert.equal(actions.find(x=>x.action==='checkpoint-persisted').turn,9047);const stop=actions.find(x=>x.action==='queued-preserving-stop-consumed');assert.equal(stop.valid,true);assert.equal(stop.ordinal,11);assert.equal(stop.runId,receipt.profile.runId);assert.equal(stop.inputSha256,sha(run+'/commands/0011.json'));assert.equal(sha(run+'/commands/0011.json'),sha(run+'/consumed-0011.json'));assert.equal(actions.at(-1).matches,true)
const prefixPath=base+'/mission-three-segment-02-erosion-prefix/actions-through-0002.jsonl',prefix=readFileSync(prefixPath),journal=readFileSync(run+'/actions.jsonl');assert.equal(hash(prefix),'17cf11e3231ece89d8f95ab02f8d77cbd2056bf83d6eafd8d42065d1e0f8bc01');assert.ok(journal.subarray(0,prefix.length).equals(prefix));const erosion=requireErosionEvidence(current,101,true);assert.equal(erosion.effects[0].onset.id,3322);assert.equal(erosion.effects[0].samples.length,64);assert.equal(erosion.effects[0].changedCells.length,99);assert.equal(erosion.effects[0].retired.turnAfter,8888)
const conversionAnchor=journey.milestones.find(x=>x.level===3&&x.name==='conversion').missionActiveSeconds,total=campaignActive(journey.epochs,current),missions=Object.fromEntries([1,2,3].map(l=>[l,campaignActive(journey.epochs,current,l)]));assert.equal(conversionAnchor,704.0833333333333);assert.equal(total,3197.3333333333335);assert.equal(missions[3],1358.3333333333333);requireCampaignBudget(journey.epochs,current,3,journey.policy.limits,conversionAnchor);assert.equal(journey.ownedWallMs,7464156);assert.equal(journey.missionWallMs[3],3834891);assert.ok(journey.ownedWallMs<journey.policy.limits.wallMs);assert.ok(journey.missionWallMs[3]<journey.policy.limits.missionWallMs[3]);assert.ok(Date.parse(outer.finishedAt)-Date.parse(outer.startedAt)<5710000)
const references=[['review-mission-one-segment-03/review.json','a4d730086b13b6813ce4b34b2a034a00eb0d9086bb6abd3578593d5c4af8aae1'],['review-mission-two-segment-01/review.json','01cb340d999396c6dff2b584ccc35a0234e7ff545c1e855a500459ad2d5fc765'],['review-mission-three-segment-01/review.json','75b1fe6111ab0f521efe93352306ddb4ea30c8a214918edf83a6d35f80649eea'],['review-mission-three-segment-02-erosion-prefix/review.json','fda40c4468286b0415a33a4a345de1775b7c9627b3431a126c0531a587446900'],['review-mission-three-segment-02-erosion-prefix/native-assessment.json','f4fd08f200f7049f61785a2d220e69ddae1fc43169d6bc786e2b35eab1b3e70d']];for(const [path,digest]of references)assert.equal(sha(base+'/'+path),digest)
const result={status:'PASS BOUNDED EVIDENCE VERIFICATION',reviewedAt:new Date().toISOString(),packetSha256:sha(packetPath),files:packet.files.length,bytes:packet.files.reduce((n,x)=>n+x.bytes,0),source:receipt.source,runId:receipt.profile.runId,profileId:receipt.profile.id,journalLines:actions.length,terminalHarnessStatus:receipt.status,browserErrors:receipt.errors,warnings:receipt.warnings.length,terminalGameStatus:terminal.status,terminalTurn:terminal.turn,profileReadbackAt:profileReads[1].at,profileSha256:profileReads[1].sha256,latestCheckpoint:saved,campaignActiveSeconds:total,missionActiveSeconds:missions,conversionAnchor,ownedWallMs:journey.ownedWallMs,missionWallMs:journey.missionWallMs,currentSegmentWallMs:journey.ownedWallMs-prior.ownedWallMs,inheritedFailureRecords:journey.failures.length,inheritedAutomaticStops:1,newAuthenticatedPreservingStops:1,newHelperFailures:0,innerSha256:sha(run+'/receipt.json'),outerSha256:sha(base+'/mission-three-segment-02.outer.json'),launcherSha256:sha(base+'/mission-three-segment-02.launcher.json'),victoryImageSha256:sha(run+'/m3-genuine-campaign-victory-result.png'),victorySnapshotSha256:sha(run+'/m3-genuine-campaign-victory-result.json'),limits:['No clean harness/campaign envelope PASS.','Mission 4 was not started.','No post-Erosion Load verifies native-land arrays.','No exact native replay, exclusive terrain attribution, calibrated timing or hardware performance claim.']}
writeFileSync(out+'/verification.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({path:out+'/verification.json',sha256:sha(out+'/verification.json'),...result}))
