import assert from 'node:assert/strict'
import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { bindGame } from '../../../scripts/browser-game.mjs'
import { waitForCheckpointReadback } from '../../../scripts/checkpoint-readback.mjs'
export default async function({page,output,signal}) {
 const events=[];
 const snap=async(name)=>{ const at=new Date().toISOString();const state=await page.evaluate(()=>{const s=window.testSceneRef.current,w=s.world;return {turn:w.turn,paused:w.paused,status:w.status,stats:w.stats,shots:w.shots,unlockedCamp:w.unlockedCamp,selected:w.selected,units:w.units.map(u=>({id:u.id,kind:u.kind,team:u.team,hp:u.hp,x:u.x,z:u.z,work:u.work,inside:u.inside})),buildings:w.buildings.map(b=>({id:b.id,kind:b.kind,team:b.team,progress:b.progress,logs:b.logs,x:b.x,z:b.z})),shrines:w.shrines.map(h=>({id:h.id,kind:h.kind,uses:h.uses,progress:h.progress})),body:document.body.innerText}});events.push({name,at,state});writeFileSync(resolve(output,'milestones.json'),JSON.stringify(events,null,2));await page.screenshot({path:resolve(output,`milestone-${name}.png`)});console.log(name,state.turn);return state;};
 const wait=async(expression,timeout=90000)=>{signal.throwIfAborted();await page.waitForFunction(expression,null,{timeout,polling:500})};
 const map=async(p)=>{const q=await page.evaluate(async p=>{const s=window.testSceneRef.current,{minimapPick}=await import('/app/minimap.ts'),r=s.mini.getBoundingClientRect(),width=s.mini.width,height=s.mini.height,center={x:Math.round((s.viewPoint.x+8)*256),y:Math.round((-s.viewPoint.z-8)*256)},target={x:Math.round((p.x+8)*256),y:Math.round((-p.z-8)*256)},heading=Math.round(s.cameraBearing*1024/Math.PI),wrap=v=>((v+32768)%65536+65536)%65536-32768;let best={d:Infinity};for(let y=2;y<height-2;y++)for(let x=2;x<width-2;x++){const n=minimapPick(width,height,center,heading,{x,y}),d=Math.hypot(wrap(n.x-target.x),wrap(n.y-target.y));if(d<best.d)best={d,x:r.x+x/width*r.width,y:r.y+y/height*r.height}}return best},p);await page.mouse.click(q.x,q.y);await page.waitForTimeout(1200);};
 const ground=async(p)=>page.evaluate(p=>{const s=window.testSceneRef.current,r=s.container.getBoundingClientRect(),q=s.screen(p);return {x:r.x+(q.x+1)*r.width/2,y:r.y+(1-q.y)*r.height/2}},p);
 const clickGround=async(p)=>{const q=await ground(p);assert.ok(q.x>200&&q.x<1440&&q.y>0&&q.y<880,JSON.stringify(q));await page.mouse.click(q.x,q.y);await page.mouse.move(400,700);};
 const entity=async(collection,id)=>{const q=await page.evaluate(({collection,id})=>{const s=window.testSceneRef.current,o=s.world[collection].find(o=>o.id===id),r=s.container.getBoundingClientRect(),p=s.screen(o),c={x:r.x+(p.x+1)*r.width/2,y:r.y+(1-p.y)*r.height/2};for(const dy of [-30,-50,-10,-70,0])for(const dx of [0,-10,10,-20,20]){const e={clientX:c.x+dx,clientY:c.y+dy};const person=s.picking.pickPerson(e);const hit=collection==='units'?person:person??s.pickWorldObject(e)?.id;if(hit===id&&document.elementFromPoint(e.clientX,e.clientY)===s.renderer.domElement)return {x:e.clientX,y:e.clientY};}throw Error('No rendered hit '+collection+' '+id)},{collection,id});await page.mouse.click(q.x,q.y);await page.mouse.move(400,700);};
 const button=(name,options)=>page.getByRole('button',{name,exact:true}).click(options);
 const pause=()=>button('Pause game'); const resume=()=>button('Resume game');
 await button('Select Mission 1');await button('Start Mission 1');await bindGame(page);await wait(()=>window.testScene.world.flyby.flags&1||!window.testScene.world.inputMask);if(await page.locator('.skip-introduction').isVisible())await page.locator('.skip-introduction').click();await wait(()=>!window.testScene.world.inputMask);
 await pause();await page.getByTitle('buildings',{exact:true}).click();assert.equal(await page.getByRole('button',{name:'Warrior Training Hut, 8 wood',exact:true}).isDisabled(),true);await snap('opening');
 await resume();await map({x:-5,z:25});await entity('shrines',29);await wait(()=>window.testSceneRef.current.world.shots.bridge>=4,120000);await snap('bridge-stock');
 await map({x:0,z:20});await clickGround({x:0,z:20});await wait(()=>{const u=window.testSceneRef.current.world.units.find(u=>u.id===30);return Math.hypot(u.x,u.z-20)<1.3},60000);
 await map({x:0,z:4});await page.getByTitle('spells',{exact:true}).click();await button('Land Bridge, 4 shots');await clickGround({x:0,z:4});await wait(()=>window.testSceneRef.current.world.stats.bridges>=1&&!window.testSceneRef.current.world.effects.some(f=>f.bridge),45000);await page.keyboard.press('Escape');await button('Select and focus shaman');await map({x:-5,z:-3});await entity('shrines',2);await wait(()=>!window.testSceneRef.current.world.units.some(u=>u.id===38&&u.hp>0),120000);await entity('shrines',2);await wait(()=>window.testSceneRef.current.world.unlockedCamp,90000);await snap('knowledge');
 await page.keyboard.press('Escape');await button('Select brave',{modifiers:['Control']});await map({x:-2,z:30});await page.getByTitle('buildings',{exact:true}).click();await button('Warrior Training Hut, 8 wood');const q=await ground({x:-2,z:30});await page.mouse.move(q.x,q.y);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.testSceneRef.current.cursor.userData.invalid),false);await clickGround({x:-2,z:30});await wait(()=>window.testSceneRef.current.world.buildings.some(b=>b.team==='blue'&&b.kind==='camp'&&b.progress===1),180000);const camp=await page.evaluate(()=>window.testSceneRef.current.world.buildings.find(b=>b.team==='blue'&&b.kind==='camp').id);await snap('built');await entity('buildings',camp);await page.waitForFunction(camp=>window.testSceneRef.current.world.units.filter(u=>u.inside===camp).length>=5,camp,{timeout:60000,polling:500});
 await button('Select and focus shaman');await map({x:11,z:1});await entity('shrines',28);await wait(()=>window.testSceneRef.current.world.shots.lightning>=4&&window.testSceneRef.current.world.stats.trained>=5,150000);await pause();await page.getByTitle('followers',{exact:true}).click();const saved=await snap('trained');assert.equal(saved.units.filter(u=>u.team==='blue'&&u.kind==='warrior').length,5);
 await button('Menu');await button('Save checkpoint');assert.equal(await waitForCheckpointReadback(()=>page.evaluate(async turn=>{const q=indexedDB.open('populous-new-dawn',1),db=await new Promise((r,j)=>{q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});try{const r=db.transaction('checkpoints','readonly').objectStore('checkpoints').get('latest'),v=await new Promise((a,b)=>{r.onsuccess=()=>a(r.result);r.onerror=()=>b(r.error)});return v?.world?.turn===turn&&v.world.stats.trained===5}finally{db.close()}},saved.turn)),true,'Committed save readback');await page.reload({waitUntil:'domcontentloaded'});await button('Load Game');await bindGame(page);await pause();await page.getByTitle('followers',{exact:true}).click();const restored=await snap('restored');assert.equal(restored.unlockedCamp,true);assert.equal(restored.buildings.find(b=>b.id===camp)?.progress,1);assert.ok(restored.turn>=saved.turn&&restored.turn<saved.turn+36);assert.deepEqual(restored.stats,saved.stats);assert.deepEqual(restored.shots,saved.shots);assert.deepEqual(restored.units.filter(u=>u.team==='blue'&&u.kind==='warrior').map(u=>u.id),saved.units.filter(u=>u.team==='blue'&&u.kind==='warrior').map(u=>u.id));
 return {saved,restored,events};
}
