"""Import mission geometry/objects from an extracted, user-supplied game.
Usage: python3 scripts/import-level.py /path/to/extracted/levels [mission]
The installer itself is never run. See references/level-one.md for extraction.
"""
import hashlib, json, struct, sys
from pathlib import Path
mission = int(sys.argv[2]) if len(sys.argv) > 2 else 1
word = {1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six', 7: 'seven', 8: 'eight', 9: 'nine'}.get(mission)
if word is None: raise ValueError('Only recovered missions 1 through 9 are supported')
src = Path(sys.argv[1]); name = f'levl{2000 + mission:04}'
data = (src / f'{name}.dat').read_bytes(); hdr = (src / f'{name}.hdr').read_bytes()
assert len(data) >= 0x2EDF3 and len(hdr) == 616, 'Unexpected level format'
heights = struct.unpack('<16384h', data[:32768])
# Native loads object coordinates as signed little-endian fixed-point words.
objects = []
for i in range(2000):
    b = data[0x14043 + i * 55:0x14043 + (i + 1) * 55]
    if not b[1]: continue
    x, z = struct.unpack_from('<hh', b, 3)
    px, pz = x / 256 - 8, -z / 256 - 8
    o = dict(index=i, model=b[0], type=b[1], owner=b[2], x=px, z=pz, angle=struct.unpack_from('<i',b,7)[0])
    if b[1] == 6: o['settings'] = list(b[7:39])
    if b[1] == 7 and b[0] == 24:
        tx, tz = struct.unpack_from('>HxxH', b, 7)
        o['target'] = {'x': ((tx / 2 if tx < 128 else tx / 2 - 128)-4)*2,
                       'z': -((tz / 2 if tz < 128 else tz / 2 - 128)+4)*2}
    objects.append(o)
if mission == 1: assert sum(o['type']==1 and o['owner']==0 and o['model']==2 for o in objects)==6
out = dict(sourceSha256=hashlib.sha256(data).hexdigest(), headerSha256=hashlib.sha256(hdr).hexdigest(), header=list(hdr[:56]), landscapeBank=hdr[96], objectBank=hdr[97], markers=list(struct.unpack_from('<256H',hdr,100)), heights=[[i%128,i//128,h] for i,h in enumerate(heights) if h], objects=objects)
Path(f'app/level-{word}.ts').write_text(f'// Generated by scripts/import-level.py from the supplied {name}.dat.\nexport default '+json.dumps(out,separators=(',',':'))+';\n')
print('Imported',len(out['heights']),'land vertices and',len(objects),'objects; SHA256',out['sourceSha256'])
