"""Export only Bloodlust HFX1478..1487 to an isolated atlas and metadata.

python scripts/import-bloodlust.py /path/to/game [--check]
No shared HUD/unit/effect atlas or global provenance is modified. --check compares
both generated byte streams without writing. Uses the existing original decoder.
"""
import argparse
import hashlib
import importlib.util
import json
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    'data/hfx0-0.dat': '681eb1734fd73f86a6a52a8540415ec69a241a378161b60e9c9da1263d4ee0bf',
    'data/pal0-c.dat': '6c61cd586fc96ef5f777c71966a9ac1875491a4a521342ba06d108df5e92bf53',
    'data/al0-c.dat': 'afc46e78b56f901f1331ceb0b02052eeaba2b6446b8747a03d0f12639ae17310',
}


def decode(game):
    raw = {name: (game / name).read_bytes() for name in SOURCES}
    for name, expected in SOURCES.items():
        if hashlib.sha256(raw[name]).hexdigest() != expected:
            raise ValueError(f'Original input hash mismatch: {name}')
    spec = importlib.util.spec_from_file_location('original_bloodlust_decoder', ROOT / 'scripts/import-original.py')
    decoder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(decoder)
    palette, alpha = raw['data/pal0-c.dat'], raw['data/al0-c.dat']
    # 00476570: upper nibble -> AL palette colour; lower nibble -> opacity.
    colors = b''.join(palette[alpha[(v | 15) * 256] * 4:alpha[(v | 15) * 256] * 4 + 3]
                      + bytes([(v & 15) * 17]) for v in range(256))
    bank = decoder.sprites(raw['data/hfx0-0.dat'], colors, alpha=True)
    frames = bank[1478:1488]
    assert len(frames) == 10 and all(w > 0 and h > 0 for w, h, _ in frames)
    cell = 1
    while cell < max(max(w, h) for w, h, _ in frames):
        cell *= 2
    width, height = cell * 10, cell
    pixels, entries = bytearray(width * height * 4), []
    for i, (w, h, data) in enumerate(frames):
        for y in range(h):
            start = (y * width + i * cell) * 4
            pixels[start:start + w * 4] = data[y * w * 4:(y + 1) * w * 4]
        entries.append(dict(source=1478+i, x=i*cell, y=0, w=w, h=h,
                            rgbaSHA256=hashlib.sha256(data).hexdigest()))
    with tempfile.TemporaryDirectory(prefix='pnd-bloodlust-') as tmp:
        path = Path(tmp) / 'bloodlust.png'
        decoder.png(path, width, height, pixels)
        image = path.read_bytes()
    metadata = dict(atlas='bloodlust', width=width, height=height, frames=entries,
                    inputSHA256=SOURCES, pngSHA256=hashlib.sha256(image).hexdigest(),
                    executableSHA256=json.loads((ROOT / 'decomp/tools.json').read_text())['executableSha256'],
                    renderer='004673b0 Bloodlust-only HFX offset0x2e30, ten presentation frames')
    return image, (json.dumps(metadata, indent=2) + '\n').encode()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('game', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    image, metadata = decode(args.game)
    outputs = {ROOT / 'public/original/bloodlust.png': image, ROOT / 'app/original-bloodlust.json': metadata}
    for path, data in outputs.items():
        if args.check:
            assert path.read_bytes() == data, f'Generated Bloodlust bytes differ: {path}'
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
    print(json.dumps(dict(status='PASS', checkOnly=args.check, frames=10,
                          files=[str(p.relative_to(ROOT)) for p in outputs])))


if __name__ == '__main__':
    main()
