"""Import just level-one geometry/objects from an extracted, user-supplied game.
Usage: python3 scripts/import-level.py /path/to/extracted/levels
The installer itself is never run. See references/level-one.md for extraction.
"""
import hashlib, json, struct, sys
from pathlib import Path
src = Path(sys.argv[1]); data = (src / 'levl2001.dat').read_bytes(); hdr = (src / 'levl2001.hdr').read_bytes()
assert len(data) >= 0x2EDF3 and len(hdr) == 616, 'Unexpected level format'
heights = struct.unpack('<16384h', data[:32768])
# Coordinates are big endian in the 55-byte object records; terrain heights are little endian.
objects = []
for i in range(2000):
    b = data[0x14043 + i * 55:0x14043 + (i + 1) * 55]
    if not b[1]: continue
    x, z = struct.unpack_from('>HH', b, 3)
    assert x < 256 and z < 256
    sx = x / 2 if x < 128 else x / 2 - 128
    sz = z / 2 if z < 128 else z / 2 - 128
    o = dict(index=i, model=b[0], type=b[1], owner=b[2], x=(sx-4)*2, z=-(sz+4)*2, angle=struct.unpack_from('<i',b,7)[0])
    if b[1] == 6: o['settings'] = list(b[7:39])
    objects.append(o)
assert sum(o['type']==1 and o['owner']==0 and o['model']==2 for o in objects)==6
out = dict(sourceSha256=hashlib.sha256(data).hexdigest(), headerSha256=hashlib.sha256(hdr).hexdigest(), header=list(hdr[:56]), landscapeBank=hdr[96], objectBank=hdr[97], markers=list(struct.unpack_from('<256H',hdr,100)), heights=[[i%128,i//128,h] for i,h in enumerate(heights) if h], objects=objects)
Path('app/level-one.ts').write_text('// Generated by scripts/import-level.py from the supplied levl2001.dat.\nexport default '+json.dumps(out,separators=(',',':'))+';\n')
print('Imported',len(out['heights']),'land vertices and',len(objects),'objects; SHA256',out['sourceSha256'])
