#!/usr/bin/env python3
"""Import only the original model45 Stone Head's raw keypoints and base indices.

python3 -B scripts/import-stone-heads.py GAME_ROOT [--check]
Writes only app/original-stone-heads.json and an additive provenance.stoneHeads entry.
No shared model, texture, unit or broad importer output is changed.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
import struct

HASHES = {
    'objects/objs0-2.dat': 'e1af6bdf050608d7c1832700826bece72ca592abdff3ee9c2138c50ed8a8607d',
    'objects/facs0-2.dat': '01a9a6d02efa0d35f7026cd97f8e01f72cbfb72e94217efe8256e8fe43597e9a',
    'objects/pnts0-2.dat': '09ebbdc9496d2ebd3a932be96af3fd27e6701a41105a5154aec4abe39e50b911',
    'objects/morph0-2.dat': '1939b4d30839f2ab49ea110abb29d40eb001d6cc6fa4932be72ce44c3aebf066',
}
ROOT = Path(__file__).resolve().parents[1]


def decode(source):
    raw = {}
    for name, expected in HASHES.items():
        data = (source / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != expected:
            raise ValueError('Canonical Stone Head input SHA mismatch: ' + name)
        raw[name] = data
    objects, faces, points, morphs = [raw[name] for name in HASHES]
    # Reuse the already-reviewed geometry decoder, not its writing/main pipeline.
    spec = importlib.util.spec_from_file_location('stone_model_decoder', ROOT / 'scripts/import-original.py')
    decoder = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(decoder)
    base, (scale, indices) = decoder.decode_original_model(objects, faces, points, 45)
    if scale != 150 or len(base['faces']) != 104:
        raise ValueError('Unexpected model45 base geometry')
    keypoints = {}
    for model in (46, 47):
        at = model * 54
        count, start = struct.unpack_from('<h', objects, at + 4)[0], struct.unpack_from('<I', objects, at + 24)[0]
        if count != 52 or start < 1 or (start + count - 1) * 6 > len(points):
            raise ValueError('Invalid original keypoint range')
        # Keep native signed shorts and order. Key faces/scale are NOT the base's.
        keypoints[str(model)] = list(struct.unpack_from('<' + str(count * 3) + 'h', points, (start - 1) * 6))
    record = 0x170
    if struct.unpack_from('<4i', morphs, record) != (45, 2, 46, 47):
        raise ValueError('Unexpected model45 morph sequence')
    if struct.unpack_from('<2i', morphs, record + 0x58) != (8, 8):
        raise ValueError('Unexpected original morph segment lengths')
    if any(index < 0 or index >= 52 for index in indices):
        raise ValueError('Base face references outside matching keypoints')
    visible_indices, cursor = [], 0
    for face, mode in enumerate(base['modes']):
        count = 3 if base['faces'][face * 2] == 3 else 6
        if mode:
            visible_indices.extend(indices[cursor:cursor + count])
        cursor += count
    if cursor != len(indices):
        raise ValueError('Incomplete base topology coverage')
    data = {
        'version': 1, 'base': 45, 'scale': scale, 'pointCount': 52, 'morphIndex': 1,
        'frames': 18, 'keypoints': keypoints, 'basePointIndices': indices,
        'visiblePointIndices': visible_indices,
        'segments': [
            {'from': 46, 'to': 47, 'first': 0, 'last': 8, 'duration': 9},
            {'from': 47, 'to': 46, 'first': 9, 'last': 17, 'duration': 9},
        ],
        'sha256': HASHES,
    }
    return data, base


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--project-root', type=Path, default=ROOT, help='Explicit isolated output project, including existing model/provenance inputs')
    parser.add_argument('--check', action='store_true', help='Verify exact generated bytes without writing')
    args = parser.parse_args()
    data, base = decode(args.source)
    project = args.project_root.resolve()
    models_path = project / 'app/original-models.json'
    provenance_path = project / 'public/original/provenance.json'
    target = project / 'app/original-stone-heads.json'
    models = json.loads(models_path.read_text())
    if models.get('45') != base:
        raise ValueError('Existing model45 faces/UV/normals/points differ from canonical decoder')
    provenance = json.loads(provenance_path.read_text())
    entry = {'baseModel': 45, 'keyModels': [46, 47], 'morphIndex': 1,
             'animationUpdates': 18, 'asset': 'app/original-stone-heads.json', 'sha256': HASHES}
    if 'stoneHeads' in provenance and provenance['stoneHeads'] != entry:
        raise ValueError('Refusing to replace differing prior Stone Head provenance')
    if target.exists() and json.loads(target.read_text()) != data:
        raise ValueError('Refusing to overwrite differing Stone Head data')
    provenance['stoneHeads'] = entry
    outputs = {target: json.dumps(data, separators=(',', ':')) + '\n',
               provenance_path: json.dumps(provenance, indent=2) + '\n'}
    if args.check:
        for file, text in outputs.items():
            if not file.exists() or file.read_bytes() != text.encode():
                raise ValueError('Generated Stone Head output differs: ' + str(file))
    else:
        for file, text in outputs.items():
            file.write_text(text, encoding='utf-8')
    print(json.dumps({'status': 'PASS_STONE_HEAD_ASSET_CHECK' if args.check else 'IMPORTED_STONE_HEAD_45_ONLY',
                      'base': 45, 'keys': [46, 47], 'rawPointsPerKey': 52,
                      'baseTriangles': len(data['basePointIndices']) // 3,
                      'visibleTriangles': len(data['visiblePointIndices']) // 3,
                      'outputs': {str(file): hashlib.sha256(text.encode()).hexdigest() for file, text in outputs.items()}}, indent=2))


if __name__ == '__main__':
    main()
