import assert from 'node:assert/strict'
import { readFileSync, existsSync, writeFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { campaignActive, requireCampaignBudget, requireLoadedCheckpoint, requireContinueBoundary, validateSegmentPredecessor } from '../../../../qa/campaign-continuity/boundaries.mjs'
const b = 'work/orchestration/campaign-continuity', o = b + '/mission-three-segment-01', read = p => JSON.parse(readFileSync(p)), hash = bytes => createHash('sha256').update(bytes).digest('hex'), sha = p => hash(readFileSync(p))
const packetPath = b + '/mission-three-segment-01-terminal-packet.json', packet = read(packetPath), inner = read(o + '/receipt.json'), journey = read(o + '/journey.json'), outer = read(b + '/mission-three-segment-01.outer.json'), launcher = read(b + '/mission-three-segment-01.launcher.json'), status = read(b + '/mission-three-segment-01-terminal-status.json')
assert.equal(sha(packetPath), 'dd7cc747b70085fe297deebf8b54345126091de78a96e59c050292a2aabe495d')
for (const f of packet.files) { assert.equal(sha(f.path), f.sha256, f.path); assert.equal(readFileSync(f.path).length, f.bytes, f.path) }
assert.equal(inner.status, 'failed'); assert.equal(outer.status, 'failed'); assert.equal(outer.exitCode, 1); assert.equal(outer.signal, null); assert.equal(launcher.commandExitCode, 1)
assert.equal(Object.hasOwn(inner, 'previousFailure'), false); assert.equal(Object.hasOwn(inner, 'campaignBoundary'), false); assert.equal(existsSync(o + '/segment-boundary.json'), false)
assert.equal(inner.failure, journey.controlStops[0].error); assert.equal(inner.failure, status.failure); assert.equal(status.receiptSha256, sha(o + '/receipt.json')); assert.equal(launcher.innerReceiptSha256, sha(o + '/receipt.json'))
assert.deepEqual(inner.source, inner.sourceAfter); assert.deepEqual(inner.runtime, inner.runtimeAfter); assert.deepEqual(inner.scenario, inner.scenarioAfter); assert.deepEqual(outer.source, outer.sourceAfter)
assert.equal(execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(), inner.source.commit); assert.equal(execFileSync('git', ['status', '--short'], { encoding: 'utf8' }), '')
for (const n of ['stdout', 'stderr']) { assert.equal(sha(outer.artifacts[n]), outer[n + 'Sha256']); assert.equal(readFileSync(outer.artifacts[n], 'utf8'), outer[n]) }
const finalBinding = read(b + '/ddef3ca-m3-final-launch-binding.json'), actual = read(b + '/ddef3ca-m3-actual-runtime.json'), expected = read(b + '/ddef3ca-m3-expected-profile-inputs.json')
for (const field of ['actualRuntime', 'sourcePreflight', 'independentExactReview', 'plan', 'launcher', 'firstBatch']) assert.equal(sha(finalBinding[field].path), finalBinding[field].sha256)
for (const key of ['source', 'runtime']) { assert.deepEqual(actual[key], expected[key]); assert.deepEqual(actual[key], inner[key]); assert.deepEqual(actual[key], launcher.sourceRuntimeVerification[key]) }
assert.deepEqual(actual.inputs, inner.profile.inputs); assert.deepEqual(actual.inputs, expected.inputs); assert.deepEqual(inner.profile.previousRun, actual.previousRun)
assert.equal(sha(actual.dependencyReturn.path), actual.dependencyReturn.sha256)
const prior = read(inner.profile.previousRun.receiptPath), priorBoundary = read(prior.campaignBoundary.path)
assert.equal(sha(inner.profile.previousRun.receiptPath), inner.profile.previousRun.receiptSha256); assert.deepEqual(inner.profile.checkpointAtStart, prior.profile.checkpointAtEnd)
assert.deepEqual(journey.failures, [...priorBoundary.failures, { kind: 'prior-harness-failure', runId: prior.profile.runId, error: prior.failure }]); assert.equal(journey.controlStops.length, 1); assert.equal(journey.controlStops[0].code, 'progress-stall'); assert.equal(journey.controlStops[0].index, 9)
assert.deepEqual(journey.epochs.slice(0, priorBoundary.epochs.length), priorBoundary.epochs); assert.deepEqual(journey.milestones.slice(0, priorBoundary.milestones.length), priorBoundary.milestones)
assert.deepEqual(inner.errors, []); assert.deepEqual(journey.browserErrors, []); assert.equal(journey.preserveStopRequested, false); assert.equal(journey.preserveVerificationFailed, false)
const actions = readFileSync(o + '/actions.jsonl', 'utf8').trim().split('\n').map(JSON.parse), inputs = new Map(journey.inputs.map(row => [row.name, row.sha256])), issued = [], skipped = []; let queued = 0
for (let n = 1; n <= 9; n++) { const file = String(n).padStart(4, '0') + '.json', path = o + '/commands/' + file, batch = read(path); assert.equal(sha(path), sha(o + '/consumed-' + file)); assert.equal(sha(path), inputs.get('commands/' + file)); queued += batch.length; const count = n === 7 || n === 9 ? 1 : batch.length; issued.push(...batch.slice(0, count)); skipped.push(...batch.slice(count).map(command => ({ batch: n, command }))) }
assert.deepEqual(issued, actions.filter(row => row.action === 'requested-command').map(row => row.command)); assert.equal(issued.length, 39); assert.equal(queued, 42)
for (const input of journey.inputs.filter(row => !row.name.startsWith('commands/') && !row.name.startsWith('/'))) { assert.equal(sha(o + '/' + input.name), input.sha256); assert.equal(sha('qa/campaign-continuity/' + input.name), input.sha256) }
for (const [path, digest] of Object.entries(journey.policy.applicationImports)) assert.equal(sha(path), digest)
const deferred = actions.find(row => row.action === 'batch-deferred-for-first-listener'); assert.equal(deferred.index, 7); assert.deepEqual(deferred.context.beforeCommand, { action: 'approach-sermon' }); assert.equal(sha(o + '/commands/0007.json'), deferred.inputSha256)
for (const row of actions.filter(row => row.action === 'entity-delivered-pointer-observation')) { assert.deepEqual(row.observed.errors, []); assert.equal(row.observed.restored, true) }
for (const proof of journey.checkpointProofs.filter(proof => proof.loaded)) { requireLoadedCheckpoint(proof.saved, proof.boundary, proof.stored); requireContinueBoundary(proof.identity, proof.level) }
assert.deepEqual(inner.profile.checkpointAtEnd, journey.protectedLatest.checkpoint); assert.equal(inner.profile.checkpointAtEnd.turn, 7424)
assert.equal(actions.at(-1).action, 'terminal-latest-preserved'); assert.equal(actions.at(-1).matches, true); assert.deepEqual(actions.at(-1).actual, inner.profile.checkpointAtEnd)
const terminal = read(o + '/terminal.json'), shrine = terminal.shrines.find(row => row.id === 101), erosion = journey.currentEpoch.erosion
assert.equal(terminal.status, 'playing'); assert.deepEqual(terminal.completedMissions, [1, 2]); assert.ok(!terminal.units.some(unit => unit.id === 3181)); assert.equal(shrine.uses, 0); assert.equal(shrine.work, 0); assert.equal(shrine.followers, 0); assert.equal(erosion.use, null); assert.deepEqual(erosion.effects, []); assert.equal(erosion.samples, 1612)
assert.ok(!journey.milestones.some(mark => mark.level === 3 && ['erosion-start', 'erosion', 'victory'].includes(mark.name)))
const guard = actions.find(row => row.action === 'diagnostic-stop'), progress = actions.filter(row => row.action === 'progress-observation' && row.condition.id === 101)
assert.equal(guard.code, 'progress-stall'); assert.ok(progress.length === 3 && progress.every(row => row.progress === guard.progress)); const changedAt = progress[0].activeSeconds - progress[0].unchangedActiveSeconds; assert.equal(guard.activeSeconds - changedAt, 120.75)
const all = [...journey.epochs, journey.currentEpoch]; for (const e of all) { assert.deepEqual(e.errors, []); assert.deepEqual(e.speedViolations, []) }
const active = campaignActive(journey.epochs, journey.currentEpoch), m3Active = campaignActive(journey.epochs, journey.currentEpoch, 3), conversionAt = journey.milestones.find(mark => mark.level === 3 && mark.name === 'conversion').missionActiveSeconds
assert.equal(active, 2692.666666666667); assert.equal(m3Active, 853.6666666666666); assert.equal(packet.caps.cumulativeActiveSeconds, active); assert.equal(packet.caps.M3ActiveSeconds, m3Active); assert.ok(conversionAt < 900)
requireCampaignBudget(journey.epochs, journey.currentEpoch, 3, journey.policy.limits, conversionAt)
assert.equal(journey.ownedWallMs, 5801958); assert.equal(journey.missionWallMs[3], 2172699)
assert.ok(inner.profile.cleanupVerified && inner.profile.continuationVerified && launcher.cleanupVerified && launcher.continuationVerified && launcher.originClosed); assert.ok(launcher.postTcp.every(row => row.port === 4375 && row.closed && row.code === 111)); assert.equal(status.ownerLockAbsent, true)
const projectedPrevious = { runId: inner.profile.runId, cleanupVerified: inner.profile.cleanupVerified, continuationVerified: inner.profile.continuationVerified }
assert.throws(() => validateSegmentPredecessor(projectedPrevious, inner, journey, { id: inner.profile.id, checkpointAtStart: inner.profile.checkpointAtEnd }, inner.source), /continued-and-saved/)
const admission = read(b + '/mission-three-first-batch-admission.json'), archived = read(b + '/mission-three-admission-host-records/receipt.json')
assert.equal(sha(b + '/mission-three-admission-host-records/attempt-01.stdin.py'), archived.attempt01.sourceSha256); assert.equal(sha(b + '/mission-three-admission-host-records/attempt-01.stderr.log'), archived.attempt01.stderrSha256); assert.equal(sha(b + '/mission-three-admission-host-records/attempt-02.stdin.py'), archived.attempt02.sourceSha256); assert.equal(sha(b + '/mission-three-first-batch-admission.json'), archived.admissionReceipt.sha256); assert.equal(admission.batchSha256, sha(o + '/commands/0001.json')); assert.deepEqual(admission.priorFailureRecords, journey.failures)
const result = { status: 'PASS BOUNDED EVIDENCE; REJECT MID-MISSION CONTINUATION', reviewedAt: new Date().toISOString(), packetSha256: sha(packetPath), packetFiles: packet.files.length, innerSha256: sha(o + '/receipt.json'), outerSha256: sha(b + '/mission-three-segment-01.outer.json'), launcherSha256: sha(b + '/mission-three-segment-01.launcher.json'), finalRuntimeBindingCorrespondence: 'Actual measurement, accepted expectation, launcher measurement and terminal before/after runtime agree; no dependency or browser binary accessed by reviewer.', commandBatches: 9, queuedCommands: queued, requestedCommands: issued.length, unexecuted: skipped, inheritedFailureRecords: journey.failures.length, newAutomaticControlStops: 1, erosionUnchangedActiveSeconds: guard.activeSeconds - changedAt, exactTotalActiveSeconds: active, missionThreeActiveSeconds: m3Active, missionThreeConversionMarkActiveSeconds: conversionAt, ownedWallMs: journey.ownedWallMs, missionWallMs: journey.missionWallMs, preservedCheckpoint: inner.profile.checkpointAtEnd, cleanupScope: 'Terminal receipt/unchanged finalizer and original launcher scoped closure verified; owner-lock absence is the retained terminal-status observation, not a fresh reviewer profile inspection.', continuationRejection: 'No campaignBoundary or segment-boundary.json; phase continued-and-saved absent; maintained validator rejects actual journey.', admissionArchiveScope: archived.provenance, admissionPausedDelaySeconds: archived.pausedDelaySeconds }
const p = b + '/review-mission-three-segment-01/verification.json'; writeFileSync(p, JSON.stringify(result, null, 2) + '\n'); console.log(JSON.stringify({ status: result.status, path: p, sha256: sha(p) }))
