import assert from 'node:assert/strict';
import { chromium } from '@playwright/test';
import * as THREE from 'three';
import { createWorld, height, curve } from '../app/model.ts';
const browser = await chromium.launch({channel:'chrome',headless:true,args:['--enable-webgl','--ignore-gpu-blocklist']});
const page = await browser.newPage({ viewport: { width: 1440, height: 960 }, deviceScaleFactor: 1 });
page.setDefaultTimeout(10000);
await page.addInitScript(() => { window.__audioStarts = 0; for (const Type of [OscillatorNode,AudioBufferSourceNode]) { const start = Type.prototype.start; Type.prototype.start = function(...args) { window.__audioStarts++; return start.apply(this,args); }; } });
const errors=[];page.on('response',r=>{if(r.status()>=400)console.log('HTTP',r.status(),r.url())});page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const cam=new THREE.PerspectiveCamera(42,1440/960,.2,500);cam.position.set(53,53,73);cam.lookAt(0,0,0);cam.updateMatrixWorld();const terrain=createWorld().terrain;
const screen=(x,z)=>{const p=new THREE.Vector3(x,height(terrain,x,z)+curve(x,z)+.1,z).project(cam);return {x:(p.x+1)*720,y:(1-p.y)*480}};
const clickWorld=async(x,z,button='left')=>{const p=screen(x,z);await page.mouse.click(p.x,p.y,{button});};
try {
 await page.goto('http://localhost:3000/',{waitUntil:'networkidle'});
 await page.locator('.loading-world').waitFor({state:'hidden'});
 await page.screenshot({path:'qa/desktop.png'});
 console.log('rendered');
 await page.getByRole('button',{name:'Enable sound',exact:true}).click();
 await page.getByRole('button',{name:'Mute sound',exact:true}).waitFor();
 assert.ok(await page.evaluate(()=>window.__audioStarts>=4),'audio gesture starts the ambience and acknowledgement sources');
 await page.getByRole('button',{name:'Convert, 20 mana',exact:true}).click();
 await clickWorld(-7,0); console.log('convert clicked',await page.locator('.world-message').innerText());
 await page.getByText('3 wildmen have joined your tribe.').waitFor();
 assert.match(await page.locator('.objective-panel').innerText(),/Welcome the wildmen/);
 assert.equal(await page.locator('.objective-panel li.complete').count(),1);
 await clickWorld(-8,9,'right');
 await page.getByText('Your followers are on the move.').waitFor();
 await page.waitForTimeout(3300);
 await page.getByRole('button',{name:'buildings B',exact:false}).click();
 await page.getByRole('button',{name:'Warrior camp, 65 wood',exact:true}).click();
 await clickWorld(-9,12);
 await page.getByText('Warrior camp planned. Your braves are building.').waitFor();
 await page.getByRole('button',{name:'2× GAME SPEED',exact:false}).count().then(async n=>{if(!n)await page.getByRole('button',{name:'1× GAME SPEED',exact:false}).click()});
 await page.waitForFunction(()=>document.querySelectorAll('.objective-panel li.complete').length>=2,{},{timeout:20000});
 await page.getByRole('button',{name:'Pause game',exact:true}).click();
 const clock=await page.locator('.clock-label').innerText();await page.waitForTimeout(400);assert.equal(await page.locator('.clock-label').innerText(),clock);
 await page.getByRole('button',{name:'Resume game',exact:true}).click();
 await page.getByRole('button',{name:'Menu',exact:true}).click();assert.equal(await page.locator('dialog').evaluate(d=>d.open),true);
 await page.getByRole('button',{name:'Return to the world',exact:false}).click();
 assert.equal(await page.locator('dialog').evaluate(d=>d.open),false);
 await page.getByRole('button',{name:'spells 1–6',exact:false}).click();
 await page.getByRole('button',{name:'Lightning, 55 mana',exact:true}).click();
 await clickWorld(3,5);
 await page.getByText('Lightning! The world bends to your will.').waitFor();
 await page.screenshot({path:'qa/lightning.png'});
 await page.getByRole('button',{name:'Mute sound',exact:true}).click();
 await page.getByRole('button',{name:'Enable sound',exact:true}).waitFor();
 await page.getByRole('button',{name:'Menu',exact:true}).click();
 await page.getByRole('button',{name:'Restart world',exact:true}).click();
 await page.locator('.loading-world').waitFor({state:'hidden'});
 assert.equal(await page.locator('.objective-panel li.complete').count(),0);
 assert.deepEqual(errors,[],'no page or console errors');
 console.log('PASS: WebGL render, sound toggle, conversion, move orders, construction, pause, speed, menu, lightning, restart, desktop controls.');
} catch(e) { await page.screenshot({path:'qa/failure.png'});console.log((await page.locator('body').innerText()).slice(0,1800));throw e; } finally {console.log(JSON.stringify({errors},null,2));await browser.close();}
